export const SET_MOVIE_TRENDING = "SET_MOVIE_TRENDING";
export const SET_MOVIE_POPULAR = "SET_MOVIE_POPULAR";
export const SET_MOVIE_TOPRATED = "SET_MOVIE_TOPRATED";
export const SET_MOVIE_UPCOMING = "SET_MOVIE_UPCOMING";
