export const SET_MOVIE_TRENDING = "SET_MOVIE_TRENDING";
export const SET_MOVIE_POPULAR = "SET_MOVIE_POPULAR";
export const SET_MOVIE_TOPRATED = "SET_MOVIE_TOPRATED";
export const SET_MOVIE_UPCOMING = "SET_MOVIE_UPCOMING";
export const SET_MOVIE_AIRING = "SET_MOVIE_AIRING";
export const SET_MOVIE_SIMILAR = "SET_MOVIE_SIMILAR";
export const SET_MOVIE_DETAIL = "SET_MOVIE_DETAIL";
