export const SET_TVSHOW_TRENDING = "SET_TVSHOW_TRENDING";
export const SET_TVSHOW_POPULAR = "SET_TVSHOW_POPULAR";
export const SET_TVSHOW_TOPRATED = "SET_TVSHOW_TOPRATED";
export const SET_TVSHOW_AIRING = "SET_TVSHOW_AIRING";
export const SET_TVSHOW_EXPLORE = "SET_TVSHOW_EXPLORE";
